apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-editor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity-editor
  template:
    metadata:
      labels:
        app: entity-editor
    spec:
      containers:
        - image: ngregor/entity-editor:latest
          name: entity-editor
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mel.db.elephantsql.com:5432/eveuoajt
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: eveuoajt
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass--rso-db-entities
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: entity-editor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: entity-editor